language: ruby
rvm:
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-19mode
script:
- bundle exec rake db:migrate
- bundle exec rake test
deploy:
  provider: heroku
  api_key:
    secure: YKfVbOA5J1c1cGqAGGleogSul9y98sK6gfLJ1B9ODFrBeJGaROtxZ/XBOS8WEcRuOIbV1yS6ZoPaHR5IXsq6fg+AY0tNEiuywT8ErFRzoIEBMl659E8IXL+l2E8J3tOT6C+GFEnLaQvP/JhQqmWn34Kb+6dxwsPeh0sZDPK/MJc=
  app: twordtag
  run:
    - bundle exec rake db:migrate
  on:
    repo: soramugi/twordtag
